syntax = "proto3";
package rong;

service ecl {
	rpc GetState(Request) returns (Reply) {}
	rpc GetScaler(Request) returns (stream Reply) {}
	rpc GetScalerRecent(RecentRequest) returns (stream Reply) {}
	rpc GetScalerDate(DateRequest) returns (stream Reply) {}
	rpc GetConfig(Request) returns (stream Expression) {}
	rpc SetConfig(stream Expression) returns (ParseResponse) {}
	rpc RunControl(Action) returns (Reply) {}
};

message Request {
	int32 type = 1;
}

message Reply {
	int32 value = 1;
}

message RecentRequest {
	int32 type = 1;
	uint32 flag = 2;
}

message DateRequest {
	int32 year = 1;
	int32 month = 2;
	int32 day = 3;
	uint32 flag = 4;
}

message Expression {
	string value = 1;
}

message ParseResponse {
	int32 value = 1;
	int32 index = 2;
	int32 position = 3;
	int32 length = 4;
}

message Action {
    int32 type = 1;
    int32 option = 2;
	int32 extra = 3;
}