site_name: XIA online GUI
site_url: https://kinstaky.github.io/easy-config-logic
site_author: kinstaky

repo_url: https://github.com/kinstaky/easy-config-logic
repo_name: kinstaky/easy-config-logic

theme:
  name: material
  palette:
    primary: deep orange
  language: zh
  features:
    - content.code.copy
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - github-callouts

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 简介: index.md
  - 硬件说明:
    - 逻辑插件: hardware/mztio.md
    - 获取插件: hardware/pixie16.md
    - 结合使用: hardware/combine.md
  - 用户指南:
    - 开始之前: user_guide/pre_install.md
    - 快速开始: user_guide/quick_start.md
    - 配置语法: user_guide/config_syntax.md
    - 配置示例: user_guide/config_examples.md
    - 进阶使用: user_guide/advanced.md
  - 开发指南:
    - 语法库: developer/syntax.md
    - 标准化库: developer/standardize.md
    - 配置库: developer/config.md
    - 执行程序: developer/standalone.md